Numpy is an extremely popular python module. It is heavily used in scientific computing.

Three (3) main benefits of numpy: 

(1)Less Memory 

(2)Fast 

(3)Convenient

In [1]:
import numpy as np
import time
import sys

In [2]:
# To show that numpy array takes less space than a python list

l = range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [3]:
# To show that numpy is fast and convenient by showing time taken to execute

SIZE = 1000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took:",(time.time()-start)*1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy took:", (time.time()-start)*1000)


python list took: 33.99252891540527
numpy took: 1.0013580322265625


In [4]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1 + a2

array([5, 7, 9])

In [5]:
a2-a1

array([3, 3, 3])

In [6]:
a1*a2

array([ 4, 10, 18])

In [7]:
a1/a2

array([0.25, 0.4 , 0.5 ])