In [3]:
#numpy is an extremely popular python module. It is heavily used in scientific computing.
# 3 main benefits of numpy: (1)Less Memory (2)Fast (3)Convenient

In [4]:
import numpy as np
import time
import sys

In [7]:
# to show that numpy array takes less space than a python list

l = range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [8]:
# to show that numpy is fast and convenient by showing time taken to execute

SIZE = 1000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took:",(time.time()-start)*1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy took:", (time.time()-start)*1000)


python list took: 58.99810791015625
numpy took: 2.001523971557617


In [9]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1 + a2

array([5, 7, 9])

In [10]:
a2-a1

array([3, 3, 3])

In [11]:
a1*a2

array([ 4, 10, 18])

In [12]:
a1/a2

array([0.25, 0.4 , 0.5 ])